"""Description

Revision ID: a8cc348862dd
Revises: 002_guest_docs
Create Date: 2026-01-30 14:53:30.972871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8cc348862dd'
down_revision: Union[str, None] = '002_guest_docs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('function_call', sa.JSON(), nullable=True))
    op.add_column('ai_chat_messages', sa.Column('function_response', sa.JSON(), nullable=True))
    op.drop_column('ai_chat_messages', 'intent')
    op.drop_column('ai_chat_messages', 'confidence')
    op.drop_column('ai_chat_messages', 'metadata_json')
    op.add_column('ai_chat_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('ai_chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('ai_chat_sessions_hotel_id_fkey', 'ai_chat_sessions', type_='foreignkey')
    op.drop_column('ai_chat_sessions', 'hotel_id')
    op.drop_column('ai_chat_sessions', 'status')
    op.add_column('payments', sa.Column('payment_ref', sa.String(length=20), nullable=False))
    op.add_column('payments', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('payments', sa.Column('method', sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'CHEQUE', 'ONLINE', 'WALLET', name='paymentmethod'), nullable=False))
    op.add_column('payments', sa.Column('gateway', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('processed_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_payments_payment_ref'), 'payments', ['payment_ref'], unique=True)
    op.create_foreign_key(None, 'payments', 'users', ['processed_by'], ['id'])
    op.drop_column('payments', 'payment_method')
    op.add_column('whatsapp_chats', sa.Column('wa_id', sa.String(length=20), nullable=False))
    op.add_column('whatsapp_chats', sa.Column('profile_name', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_chats', sa.Column('is_bot_active', sa.Boolean(), nullable=False))
    op.add_column('whatsapp_chats', sa.Column('human_takeover_requested', sa.Boolean(), nullable=False))
    op.add_column('whatsapp_chats', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('whatsapp_chats', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('whatsapp_chats', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('whatsapp_chats', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('whatsapp_chats', sa.Column('unread_count', sa.Integer(), nullable=True))
    op.alter_column('whatsapp_chats', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'RESOLVED', 'PENDING_HUMAN', 'CLOSED', name='chatstatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_whatsapp_chats_wa_id'), 'whatsapp_chats', ['wa_id'], unique=False)
    op.drop_constraint('whatsapp_chats_hotel_id_fkey', 'whatsapp_chats', type_='foreignkey')
    op.create_foreign_key(None, 'whatsapp_chats', 'users', ['assigned_to'], ['id'])
    op.drop_column('whatsapp_chats', 'hotel_id')
    op.add_column('whatsapp_messages', sa.Column('message_id', sa.String(length=100), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('is_bot_message', sa.Boolean(), nullable=False))
    op.add_column('whatsapp_messages', sa.Column('sent_by', sa.Integer(), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.alter_column('whatsapp_messages', 'direction',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'),
               existing_nullable=False)
    op.alter_column('whatsapp_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('whatsapp_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('whatsapp_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'sent'::character varying"))
    op.create_index(op.f('ix_whatsapp_messages_message_id'), 'whatsapp_messages', ['message_id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_messages', 'users', ['sent_by'], ['id'])
    op.drop_column('whatsapp_messages', 'wa_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('wa_message_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'whatsapp_messages', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_messages_message_id'), table_name='whatsapp_messages')
    op.alter_column('whatsapp_messages', 'status',
               existing_type=sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('whatsapp_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('whatsapp_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('whatsapp_messages', 'direction',
               existing_type=sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('whatsapp_messages', 'read_at')
    op.drop_column('whatsapp_messages', 'delivered_at')
    op.drop_column('whatsapp_messages', 'sent_at')
    op.drop_column('whatsapp_messages', 'sent_by')
    op.drop_column('whatsapp_messages', 'is_bot_message')
    op.drop_column('whatsapp_messages', 'message_id')
    op.add_column('whatsapp_chats', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'whatsapp_chats', type_='foreignkey')
    op.create_foreign_key('whatsapp_chats_hotel_id_fkey', 'whatsapp_chats', 'hotels', ['hotel_id'], ['id'])
    op.drop_index(op.f('ix_whatsapp_chats_wa_id'), table_name='whatsapp_chats')
    op.alter_column('whatsapp_chats', 'status',
               existing_type=sa.Enum('ACTIVE', 'RESOLVED', 'PENDING_HUMAN', 'CLOSED', name='chatstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('whatsapp_chats', 'unread_count')
    op.drop_column('whatsapp_chats', 'last_message_at')
    op.drop_column('whatsapp_chats', 'language')
    op.drop_column('whatsapp_chats', 'context')
    op.drop_column('whatsapp_chats', 'assigned_to')
    op.drop_column('whatsapp_chats', 'human_takeover_requested')
    op.drop_column('whatsapp_chats', 'is_bot_active')
    op.drop_column('whatsapp_chats', 'profile_name')
    op.drop_column('whatsapp_chats', 'wa_id')
    op.add_column('payments', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_payment_ref'), table_name='payments')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'processed_by')
    op.drop_column('payments', 'refunded_at')
    op.drop_column('payments', 'refund_reason')
    op.drop_column('payments', 'refund_amount')
    op.drop_column('payments', 'gateway')
    op.drop_column('payments', 'method')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'payment_ref')
    op.add_column('ai_chat_sessions', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ai_chat_sessions_hotel_id_fkey', 'ai_chat_sessions', 'hotels', ['hotel_id'], ['id'])
    op.alter_column('ai_chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('ai_chat_sessions', 'is_active')
    op.drop_column('ai_chat_sessions', 'summary')
    op.add_column('ai_chat_messages', sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_chat_messages', sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('ai_chat_messages', sa.Column('intent', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('ai_chat_messages', 'function_response')
    op.drop_column('ai_chat_messages', 'function_call')
    op.drop_column('ai_chat_messages', 'tokens_used')
    # ### end Alembic commands ###
